<?php

use  console\migrations\fid\components\Migration;

/**
 * Handles the creation of table `notify`.
 */
class m170726_140542_create_notify_table extends Migration
{
    const TABLE_NAME = '{{%notify}}';
    const CASE_TYPE_TABLE_NAME = '{{%case_type}}';
    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTableWithBlameAndTimestamp(self::TABLE_NAME, [
            'id' => $this->bigInteger()->notNull(),
            'name' => $this->string(),
            'notify_choice' => $this->string(50),
            'notify_no' => $this->string(50),
            'write_at' => $this->string(),
            'notify_date' => $this->dateTime(),
            'notify_from' => $this->string(),
            'notify_from_type' => $this->smallInteger(),
            'case_type_id' => [
                'type' => $this->bigInteger(),
                'fk' => self::CASE_TYPE_TABLE_NAME,
            ],
            'case_type_other' => $this->string(),
            'location_text' => $this->text(),
            'sdate' => $this->date(),
            'stime' => $this->time(),
            'edate' => $this->date(),
            'etime' => $this->time(),
            'time_total' => $this->string(100),
            'desc' => $this->text(),
            'emp_name' => $this->string(),
            'emp_tel' => $this->string(50),
            'sufferer_name' => $this->string(),
            'sufferer_tel' => $this->string(50),
            'content' =>'longtext DEFAULT NULL',
            'status' => $this->boolean()->defaultValue(true)->notNull(),
        ]);
        $this->addPrimaryKeyWithAutoGeneratedName(self::TABLE_NAME,'id');      
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable('notify');
    }
}
